name: Test Org Runner

on: [push]

jobs:
  org-runner-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Running on organization-level self-hosted runner!"

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: org-runner-test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker image
        run: |
    # Generate unique tag (timestamp + short SHA)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION="${TIMESTAMP}-${SHORT_SHA}"

    # Build with version tag
          docker build -t ghcr.io/visiobook-esp/core-api-gateway:$VERSION ./poc

    # Also tag as latest
          docker tag ghcr.io/visiobook-esp/core-api-gateway:$VERSION ghcr.io/visiobook-esp/core-api-gateway:latest

    # Push both tags
          docker push ghcr.io/visiobook-esp/core-api-gateway:$VERSION
          docker push ghcr.io/visiobook-esp/core-api-gateway:latest

    # Store version for subsequent steps
          echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV
